version: '3'
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8001
    environment:
      DJANGO_SETTINGS_MODULE: server.settings.prod
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8001
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh
  
  web2:
    container_name: web2
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8002
    environment:
      DJANGO_SETTINGS_MODULE: server.settings.prod
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8002
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh
    depends_on:
      - web
  
  web3:
    container_name: web3
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8003
    environment:
      DJANGO_SETTINGS_MODULE: server.settings.prod
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8003
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh
    depends_on:
      - web2

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
      - /etc/letsencrypt/archive/chatminder.app-0002:/etc/nginx/conf.d/certificate
      - /home/ubuntu/srv/ubuntu/server/static:/etc/nginx/conf.d/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web3


volumes:
  static:
  media: