# Generated by Django 3.0.8 on 2022-01-04 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220103_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='url',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Memo')),
            ],
            options={
                'db_table': 'link',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='%Y/%m/%d')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Memo')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
