# Generated by Django 3.0.8 on 2022-01-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.Memo'),
        ),
    ]
