# Generated by Django 3.0.8 on 2022-01-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220101_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]