# Generated by Django 3.0.8 on 2022-01-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220104_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
