# Generated by Django 3.0.8 on 2022-01-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='anonymous', max_length=40),
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(default='url'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
