# Generated by Django 3.0.8 on 2022-01-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_color',
            field=models.CharField(blank=True, choices=[('RD', 'red'), ('GR', 'green'), ('BL', 'blue')], max_length=2, null=True),
        ),
    ]
