# Generated by Django 3.0.8 on 2022-01-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220104_2300'),
        ('app', '0010_auto_20220104_1620'),
    ]

    operations = [
    ]
