# Generated by Django 3.0.8 on 2022-01-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220107_0156'),
        ('app', '0015_image_user'),
    ]

    operations = [
    ]
