# Generated by Django 3.0.8 on 2022-01-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge_20220107_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
