# Generated by Django 3.0.8 on 2022-01-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_memo_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='is_tag_new',
        ),
    ]
