# Generated by Django 3.0.8 on 2022-01-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_memo_is_tag_new'),
        ('app', '0019_memo_has_image'),
    ]

    operations = [
    ]
