# Generated by Django 3.0.8 on 2022-01-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_merge_20220110_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
